### ISSUE TITLE
Multiple FFQs not allowed

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#493]
From the logs:

```
[2022-11-18 13:20:44 -0800] [7402] [ERROR] Exception on /api/admin/account_barcode_summary [POST]
Traceback (most recent call last):
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/security.py", line 327, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/api_user/microsetta-private-api-2022.11.2/microsetta_private_api/admin/admin_impl.py", line 504, in query_barcode_stats
    results = {'samples': per_sample(None, barcodes, strip_sampleid)}
  File "/Users/api_user/microsetta-private-api-2022.11.2/microsetta_private_api/admin/sample_summary.py", line 69, in per_sample
    ffq_complete, ffq_taken, _ = vs_repo.get_ffq_status_by_sample(
  File "/Users/api_user/microsetta-private-api-2022.11.2/microsetta_private_api/repo/vioscreen_repo.py", line 197, in get_ffq_status_by_sample
    raise ValueError("A sample should not have multiple FFQs")
ValueError: A sample should not have multiple FFQs
```

**Comment by cassidysymons** [comment]
Resolved by https://github.com/biocore/microsetta-private-api/pull/581
