### ISSUE TITLE
Error on activation code search

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#494]
From the logs:

```
[2022-10-25 08:55:31 -0700] [32629] [ERROR] Exception on /api/admin/search/activation [GET]
Traceback (most recent call last):
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/security.py", line 327, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/response.py", line 103, in wrapper
    response = function(request)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/microsetta_private_api/admin/admin_impl.py", line 588, in search_activation
    infos = activations.search_code(code_query)
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/microsetta_private_api/repo/activation_repo.py", line 19, in search_code
    cur.execute(
  File "/Users/api_user/miniconda3/envs/microsetta-private-api/lib/python3.8/site-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
TypeError: not all arguments converted during string formatting
```

**Comment by cassidysymons** [comment]
Closing this issue since activation codes are no longer in use.
